// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNOXeY8dFkRtw960MLlfrFA4-uWgftf2Q',
    appId: '1:1079529725027:web:83cf422e81a8f83399ac56',
    messagingSenderId: '1079529725027',
    projectId: 'funhub-fde63',
    authDomain: 'funhub-fde63.firebaseapp.com',
    storageBucket: 'funhub-fde63.firebasestorage.app',
    measurementId: 'G-147XFC0B73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEYLuV96rqQ1YOehUViAeBYiwNBdR2Rzw',
    appId: '1:1079529725027:android:a934e25da4fc025399ac56',
    messagingSenderId: '1079529725027',
    projectId: 'funhub-fde63',
    storageBucket: 'funhub-fde63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7bcnvpz5JBe3dWXPTlq6Q3R_QlplTUcM',
    appId: '1:1079529725027:ios:9c393958a64c26ff99ac56',
    messagingSenderId: '1079529725027',
    projectId: 'funhub-fde63',
    storageBucket: 'funhub-fde63.firebasestorage.app',
    iosBundleId: 'com.example.fungame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7bcnvpz5JBe3dWXPTlq6Q3R_QlplTUcM',
    appId: '1:1079529725027:ios:9c393958a64c26ff99ac56',
    messagingSenderId: '1079529725027',
    projectId: 'funhub-fde63',
    storageBucket: 'funhub-fde63.firebasestorage.app',
    iosBundleId: 'com.example.fungame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNOXeY8dFkRtw960MLlfrFA4-uWgftf2Q',
    appId: '1:1079529725027:web:20aa7d66c8b7855a99ac56',
    messagingSenderId: '1079529725027',
    projectId: 'funhub-fde63',
    authDomain: 'funhub-fde63.firebaseapp.com',
    storageBucket: 'funhub-fde63.firebasestorage.app',
    measurementId: 'G-K2LLHQWSF1',
  );
}
